// Common names (and a few frequent alt-names) travelers would type, mapped to ISO 639-1 codes.
// Node/browser Intl has no built-in name->code lookup, so this is a curated table rather than
// the full ISO 639 list, which is mostly obscure/historical codes not useful for a phrasebook.
const LANGUAGE_NAME_TO_CODE: Record<string, string> = {
  english: 'en',
  vietnamese: 'vi',
  indonesian: 'id',
  thai: 'th',
  khmer: 'km',
  cambodian: 'km',
  lao: 'lo',
  laotian: 'lo',
  malay: 'ms',
  tagalog: 'tl',
  filipino: 'tl',
  burmese: 'my',
  mandarin: 'zh',
  'mandarin chinese': 'zh',
  chinese: 'zh',
  cantonese: 'yue',
  japanese: 'ja',
  korean: 'ko',
  hindi: 'hi',
  bengali: 'bn',
  urdu: 'ur',
  nepali: 'ne',
  sinhala: 'si',
  sinhalese: 'si',
  tamil: 'ta',
  telugu: 'te',
  spanish: 'es',
  french: 'fr',
  german: 'de',
  italian: 'it',
  portuguese: 'pt',
  dutch: 'nl',
  greek: 'el',
  turkish: 'tr',
  russian: 'ru',
  ukrainian: 'uk',
  polish: 'pl',
  czech: 'cs',
  slovak: 'sk',
  hungarian: 'hu',
  romanian: 'ro',
  bulgarian: 'bg',
  croatian: 'hr',
  serbian: 'sr',
  slovenian: 'sl',
  swedish: 'sv',
  norwegian: 'no',
  danish: 'da',
  finnish: 'fi',
  icelandic: 'is',
  arabic: 'ar',
  hebrew: 'he',
  farsi: 'fa',
  persian: 'fa',
  swahili: 'sw',
  afrikaans: 'af',
  amharic: 'am',
  zulu: 'zu',
  xhosa: 'xh',
  welsh: 'cy',
  irish: 'ga',
  catalan: 'ca',
  basque: 'eu',
}

/** Resolves a common language name (e.g. "Thai") to its ISO 639-1 code (e.g. "th"). */
export function resolveLanguageCode(name: string): string | null {
  const target = name.trim().toLowerCase()
  return LANGUAGE_NAME_TO_CODE[target] ?? null
}
